apiVersion: v1
kind: Service
metadata:
  name: {{ include "recallq.fullname" . }}
  labels:
    {{- include "recallq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
